### ISSUE TITLE
Cleartext support is now available in rpgp

### ISSUE THREAD

**Issue by dignifiedquire** [indygreg/cryptography-rs#22]
Just merged and published in the [latest alpha](https://github.com/rpgp/rpgp/releases/tag/v0.12.0-alpha.2) full support for the cleartext framework: https://github.com/rpgp/rpgp/issues/122

**Comment by indygreg** [comment]
Great news! Thank you for introducing this feature. I'll update the README to recommend using `pgp` directly, making this crate soft deprecated.
